export type BrandType = 'lounge' | 'pod' | 'hotel' | 'hybrid';

export type OperatorModel =
  | 'independent'
  | 'airline-linked'
  | 'hospitality-group'
  | 'self-service'
  | 'mixed';

export type PricingLevel = 'low' | 'mid' | 'high' | 'premium';

export type PrivacyLevel = 'low' | 'medium' | 'high';

export type SleepQualityScore = 1 | 2 | 3 | 4 | 5;

export interface BrandRecord {
  slug: string;
  name: string;
  type: BrandType;
  operatorModel: OperatorModel;
  regions: string[];
  airportCodes: string[];
  airportCount: number;
  facilityCount: number;
  strongestHubs: string[];
  accessTypes: string[];
  airsideTypical: boolean;
  transitFriendly: boolean;
  pricingLevel: PricingLevel;
  privacyLevel: PrivacyLevel;
  sleepQualityScore: SleepQualityScore;
  bestUseCases: string[];
  limitations: string[];
  keyDifferentiator: string;
  amenitySignals: string[];
  compareCandidates: string[];
  coverageNote?: string;
  entryNuance?: string;
  sleepNuance?: string;
  trustNote?: string;
}

export const BRAND_DATA: Record<string, BrandRecord> = {
  'aerotel': {
    slug: 'aerotel',
    name: 'Aerotel',
    type: 'hotel',
    operatorModel: 'hospitality-group',
    regions: ['Asia', 'Middle East', 'Europe'],
    airportCodes: ['SIN', 'LHR', 'AUH'],
    airportCount: 3,
    facilityCount: 3,
    strongestHubs: ['Singapore Changi (SIN)', 'London Heathrow (LHR)', 'Abu Dhabi (AUH)'],
    accessTypes: ['front-desk'],
    airsideTypical: true,
    transitFriendly: true,
    pricingLevel: 'premium',
    privacyLevel: 'high',
    sleepQualityScore: 5,
    bestUseCases: [
      'Layovers of 4+ hours needing real recovery',
      'Passengers who cannot exit without a visa',
      'Travelers wanting a proper bed and shower mid-transit',
    ],
    limitations: [
      'Higher cost than pod options',
      'Advance booking required during peak seasons',
      'Limited to 3 major hub airports',
    ],
    keyDifferentiator: 'Hotel-quality private rooms with en-suite showers fully inside the secure airside zone — no immigration clearance required.',
    amenitySignals: ['private room', 'en-suite shower', 'real bed', 'desk', 'Wi-Fi', 'hourly booking'],
    compareCandidates: ['yotelair', 'minute-suites', 'napcabs', 'gosleep', 'plaza-premium'],
    coverageNote: 'Operates at SIN, LHR, and AUH only — route must pass through one of these three airports.',
    entryNuance: 'Fully airside at all locations. No transit visa needed to access rooms.',
    sleepNuance: 'Real hotel bed with blackout curtains and en-suite bathroom. Closest to an off-airport hotel experience inside a terminal.',
    trustNote: 'One of the most established airside transit hotel brands globally, operating since the 1990s at Singapore Changi.',
  },

  'gosleep': {
    slug: 'gosleep',
    name: 'GoSleep',
    type: 'pod',
    operatorModel: 'self-service',
    regions: ['Europe', 'Middle East', 'Asia'],
    airportCodes: ['HEL', 'AMS', 'DXB', 'DOH'],
    airportCount: 8,
    facilityCount: 10,
    strongestHubs: ['Helsinki Airport (HEL)', 'Amsterdam Schiphol (AMS)', 'Dubai International (DXB)'],
    accessTypes: ['self-service'],
    airsideTypical: true,
    transitFriendly: true,
    pricingLevel: 'low',
    privacyLevel: 'medium',
    sleepQualityScore: 3,
    bestUseCases: [
      'Short layovers of 1–4 hours',
      'Budget travelers who need a quick rest',
      'Passengers who want zero booking friction',
    ],
    limitations: [
      'Visor provides partial privacy only — not a sealed capsule',
      'Terminal noise remains audible through the visor',
      'No shower access built into pod units',
    ],
    keyDifferentiator: 'Finnish-designed walk-up pods with privacy visor — no check-in, no booking, operational within 60 seconds of arrival.',
    amenitySignals: ['privacy visor', 'flat-recline seat', 'wake-up alarm', 'hourly billing', 'no booking needed'],
    compareCandidates: ['napcabs', 'izzleep', 'zzzleepandgo', 'aerotel', 'sleepover'],
    coverageNote: 'Concentrated in northern Europe and Middle East Gulf hubs. Most prevalent in Scandinavian and Nordic airports.',
    entryNuance: 'Walk up, pay, rest. No staff interaction or advance reservation at any location.',
    sleepNuance: 'Flat-recline seat with visor — adequate for napping, not ideal for deep sleep or noise-sensitive travelers.',
    trustNote: 'Established pod brand with a decade-plus deployment track record at Helsinki and select Gulf airports.',
  },

  'yotelair': {
    slug: 'yotelair',
    name: 'YOTELAIR',
    type: 'hotel',
    operatorModel: 'hospitality-group',
    regions: ['Europe', 'North America'],
    airportCodes: ['AMS', 'LGW', 'LHR', 'CDG', 'JFK'],
    airportCount: 5,
    facilityCount: 5,
    strongestHubs: ['Amsterdam Schiphol (AMS)', 'Paris CDG (CDG)', 'London Heathrow (LHR)', 'New York JFK (JFK)'],
    accessTypes: ['front-desk'],
    airsideTypical: true,
    transitFriendly: true,
    pricingLevel: 'premium',
    privacyLevel: 'high',
    sleepQualityScore: 5,
    bestUseCases: [
      'Long-haul layovers on transatlantic or European routes',
      'Business and premium economy travelers',
      'Passengers wanting hotel-grade rest without leaving departures',
    ],
    limitations: [
      'Premium pricing — among the most expensive airside options',
      'Cabins book out quickly at hub airports',
      'No presence in Asia or the Middle East',
    ],
    keyDifferentiator: 'Fully private cabins with SmartBed, rainfall shower, and in-room entertainment — the benchmark for airside hotel quality in Europe.',
    amenitySignals: ['SmartBed', 'rainfall shower', 'lockable cabin', 'in-room entertainment', 'Wi-Fi', 'fresh linen'],
    compareCandidates: ['aerotel', 'minute-suites', 'napcabs', 'plaza-premium', 'kepler-club'],
    coverageNote: 'Strongest in Western Europe — AMS, CDG, LHR, LGW — plus JFK for transatlantic routing.',
    entryNuance: 'Check-in at the YOTELAIR front desk. Hourly minimum applies; overnight rates offer better per-hour value.',
    sleepNuance: 'Lockable SmartBed cabin with blackout blinds and sound insulation. Comparable sleep quality to a 3-star city hotel.',
    trustNote: 'Premium brand with strong reputation at Schiphol and Heathrow. Frequently cited in business travel press.',
  },

  'napcabs': {
    slug: 'napcabs',
    name: 'Napcabs',
    type: 'pod',
    operatorModel: 'independent',
    regions: ['Europe'],
    airportCodes: ['MUC'],
    airportCount: 2,
    facilityCount: 2,
    strongestHubs: ['Munich Airport T1 (MUC)', 'Munich Airport T2 (MUC)'],
    accessTypes: ['self-service'],
    airsideTypical: true,
    transitFriendly: true,
    pricingLevel: 'mid',
    privacyLevel: 'high',
    sleepQualityScore: 4,
    bestUseCases: [
      'Light sleepers who need genuine blackout conditions',
      'Overnight layovers at Munich Airport',
      'Travelers wanting maximum pod privacy without hotel-tier pricing',
    ],
    limitations: [
      'Available only at Munich Airport Terminal 1 and Terminal 2',
      'No in-cabin shower — adjacent shower facilities only',
      'Only useful for travelers routing through MUC',
    ],
    keyDifferentiator: 'Fully lockable, fully sealed capsules with genuine blackout — the highest privacy standard available in a pod format in Europe.',
    amenitySignals: ['lockable door', 'blackout conditions', 'noise reduction', 'flat sleep surface', 'hourly billing'],
    compareCandidates: ['gosleep', 'izzleep', 'yotelair', 'zzzleepandgo', 'aerotel'],
    coverageNote: 'Munich-only operation. T1 and T2 installations cover both main terminal zones airside.',
    entryNuance: 'Self-service booking at the pod terminal. No staff required. Accepts card payments.',
    sleepNuance: 'Sealed capsule with hard door — full blackout and meaningfully better noise suppression than visor designs.',
    trustNote: 'Long-running installation at MUC with a strong traveler review record for sleep quality among pod formats.',
  },

  'plaza-premium': {
    slug: 'plaza-premium',
    name: 'Plaza Premium',
    type: 'lounge',
    operatorModel: 'independent',
    regions: ['Asia', 'Middle East', 'Europe', 'North America'],
    airportCodes: ['HKG', 'KUL', 'SIN', 'PEK', 'DXB', 'LHR', 'JFK'],
    airportCount: 45,
    facilityCount: 100,
    strongestHubs: ['Hong Kong (HKG)', 'Kuala Lumpur (KUL)', 'Singapore (SIN)', 'Beijing (PEK)'],
    accessTypes: ['paid-entry', 'card-access'],
    airsideTypical: true,
    transitFriendly: true,
    pricingLevel: 'mid',
    privacyLevel: 'low',
    sleepQualityScore: 2,
    bestUseCases: [
      'Travelers without airline lounge access needing food and a shower',
      'Long layovers at Asia-Pacific hub airports',
      'Passengers with Priority Pass or compatible card benefits',
    ],
    limitations: [
      'Walk-in fees can reach premium levels at peak times',
      'Not designed for sleep — rest chairs are supplementary',
      'Quality varies significantly across its 100+ location network',
    ],
    keyDifferentiator: 'The world\'s largest independent airport lounge network — 100+ locations open to any passenger without airline status or ticket class restriction.',
    amenitySignals: ['hot food buffet', 'showers', 'Wi-Fi', 'quiet seating', 'Priority Pass eligible', 'rest zones'],
    compareCandidates: ['kepler-club', 'miracle', 'aerotel', 'yotelair', 'sh-premium-lounge'],
    coverageNote: 'Exceptional Asia-Pacific density. HKG, KUL, and SIN properties are flagship-grade. North American and European properties are smaller in scale.',
    entryNuance: 'Paid walk-in, Priority Pass, Lounge Key, and select credit card access. Some locations require separate shower booking on arrival.',
    sleepNuance: 'Rest chairs available but not dedicated sleep infrastructure. Lounge seating — not a pod or room product.',
    trustNote: 'Global benchmark for independent lounge access. Widely integrated into credit card travel benefits programs.',
  },

  'minute-suites': {
    slug: 'minute-suites',
    name: 'Minute Suites',
    type: 'hotel',
    operatorModel: 'independent',
    regions: ['North America'],
    airportCodes: ['ATL', 'PHL', 'DFW', 'CLT'],
    airportCount: 5,
    facilityCount: 6,
    strongestHubs: ['Atlanta Hartsfield-Jackson (ATL)', 'Dallas Fort Worth (DFW)', 'Philadelphia (PHL)', 'Charlotte Douglas (CLT)'],
    accessTypes: ['front-desk'],
    airsideTypical: true,
    transitFriendly: false,
    pricingLevel: 'mid',
    privacyLevel: 'high',
    sleepQualityScore: 4,
    bestUseCases: [
      'Business travelers needing a private space for calls or work during a US layover',
      'Families with young children on domestic connections',
      'Anyone needing guaranteed quiet and privacy at a US hub airport',
    ],
    limitations: [
      'US domestic terminal coverage only — no value for international routing',
      'Shower is an optional add-on, not standard in base rate',
      'Limited to select hub airports — unavailable at most US airports',
    ],
    keyDifferentiator: 'The only private enclosed day suite product inside the US domestic terminal network — equally suited to work, calls, and sleep.',
    amenitySignals: ['daybed sofa', 'work desk', 'television', 'Wi-Fi', 'fully enclosed suite', 'hourly billing', 'optional shower add-on'],
    compareCandidates: ['aerotel', 'yotelair', 'napcabs', 'gosleep', 'kepler-club'],
    coverageNote: 'US domestic focus at ATL, DFW, PHL, CLT. ATL is the highest-traffic location. International travelers must confirm terminal access.',
    entryNuance: 'Front desk booking — walk-in or advance reservation. Minimum one hour, no mandatory multi-hour window.',
    sleepNuance: 'Daybed converts to flat sleep surface. Fully enclosed with door lock. Quiet HVAC. Functional for proper napping or short overnight.',
    trustNote: 'Well-regarded among US frequent domestic travelers. Consistent positive reviews for privacy and convenience at ATL.',
  },

  'miracle': {
    slug: 'miracle',
    name: 'Miracle',
    type: 'lounge',
    operatorModel: 'independent',
    regions: ['Asia'],
    airportCodes: ['BKK'],
    airportCount: 1,
    facilityCount: 4,
    strongestHubs: ['Bangkok Suvarnabhumi (BKK)'],
    accessTypes: ['paid-entry'],
    airsideTypical: true,
    transitFriendly: true,
    pricingLevel: 'mid',
    privacyLevel: 'low',
    sleepQualityScore: 2,
    bestUseCases: [
      'Passengers transiting through Bangkok Suvarnabhumi needing food and a shower',
      'Travelers without Thai Airways or Bangkok Airways lounge credentials',
      'Anyone wanting a premium break at BKK without airline status',
    ],
    limitations: [
      'Single-airport brand — exclusively at Bangkok Suvarnabhumi',
      'Rest zones are lounge seating only, not dedicated sleep pods',
    ],
    keyDifferentiator: 'Dominant independent lounge operator at Bangkok Suvarnabhumi — multiple tier locations spread across BKK terminals, open to any passenger.',
    amenitySignals: ['Business Class tier', 'First Class tier', 'hot food', 'showers', 'rest chairs', 'airside access'],
    compareCandidates: ['plaza-premium', 'kepler-club', 'encalm', 'sh-premium-lounge', 'skyhub-lounge'],
    coverageNote: 'Four lounge locations across BKK terminal zones — good gate proximity for most international departures.',
    entryNuance: 'Paid per visit, tiered pricing by lounge class. Walk-in available; pre-booking via lounge platforms recommended during peak season.',
    sleepNuance: 'Rest chairs in designated zones — not a dedicated sleep product. Suitable for upright napping during a 2–4 hour transit.',
    trustNote: 'Established BKK institution with long operating history. Frequently recommended by Thailand transit travelers in travel forums.',
  },

  'izzleep': {
    slug: 'izzleep',
    name: 'izZzleep',
    type: 'pod',
    operatorModel: 'independent',
    regions: ['Europe', 'Asia'],
    airportCodes: [],
    airportCount: 1,
    facilityCount: 1,
    strongestHubs: [],
    accessTypes: ['self-service'],
    airsideTypical: true,
    transitFriendly: true,
    pricingLevel: 'mid',
    privacyLevel: 'high',
    sleepQualityScore: 4,
    bestUseCases: [
      'Travelers wanting full pod enclosure at mid-tier pricing',
      'Medium to long layovers where sleep quality takes priority over cost',
      'Passengers who find open-visor pods insufficient for real rest',
    ],
    limitations: [
      'Limited airport coverage — expansion in progress',
      'No shower access within the capsule unit',
      'Specific airport availability must be confirmed before travel',
    ],
    keyDifferentiator: 'Fully enclosed climate-controlled capsules with secure internal luggage storage — higher sleep quality than visor pods, lower cost than transit hotel rooms.',
    amenitySignals: ['fully enclosed capsule', 'climate control', 'adjustable lighting', 'secure luggage storage', 'flat sleep surface', 'hourly billing'],
    compareCandidates: ['gosleep', 'napcabs', 'zzzleepandgo', 'aerotel', 'sleepover'],
    coverageNote: 'Actively expanding network — verify live airport availability on RestInAirport before travel.',
    entryNuance: 'Self-service booking at the capsule terminal. No advance reservation required at most locations.',
    sleepNuance: 'Full enclosure with door seal. Climate control and adjustable lighting allow real sleep customization unavailable in visor-type pods.',
    trustNote: 'Newer brand with growing positive reception — strongest reviews focus on the climate control and storage features.',
  },

  'encalm': {
    slug: 'encalm',
    name: 'Encalm',
    type: 'hybrid',
    operatorModel: 'hospitality-group',
    regions: ['Asia'],
    airportCodes: ['DEL'],
    airportCount: 1,
    facilityCount: 3,
    strongestHubs: ['Delhi Indira Gandhi International (DEL)'],
    accessTypes: ['paid-entry', 'front-desk'],
    airsideTypical: true,
    transitFriendly: true,
    pricingLevel: 'mid',
    privacyLevel: 'high',
    sleepQualityScore: 4,
    bestUseCases: [
      'Passengers transiting through Delhi with a 3–12 hour layover',
      'Travelers who want to select rest tier (lounge, pod, or room) at one operator',
      'Those needing a full-service facility without navigating multiple brands',
    ],
    limitations: [
      'Single hub only — exclusively at Delhi Indira Gandhi Airport',
      'No multi-airport utility for routes not passing through DEL',
    ],
    keyDifferentiator: "India's only all-in-one transit hospitality operator — lounge, sleep pod, and hotel room available under one brand at DEL.",
    amenitySignals: ['lounge tier', 'pod tier', 'hotel room tier', 'showers', 'hot food', 'tiered pricing'],
    compareCandidates: ['miracle', 'plaza-premium', 'aerotel', 'kepler-club', 'sh-premium-lounge'],
    coverageNote: 'Delhi-only. All three service tiers (lounge, pod, hotel room) are in the airside international transit zone.',
    entryNuance: 'Lounge access is walk-in paid entry. Pod and hotel room tiers are booked at the facility reception or online. All tiers are airside.',
    sleepNuance: 'Hotel room tier offers full private room with proper bed and shower. Pod tier offers enclosed capsule sleep. Lounge tier offers rest chairs only.',
    trustNote: 'Leading transit hospitality operator in the Indian airport market. Well-reviewed for its multi-tier flexibility at DEL.',
  },

  'zzzleepandgo': {
    slug: 'zzzleepandgo',
    name: 'ZZZleepandGo',
    type: 'pod',
    operatorModel: 'self-service',
    regions: ['Europe'],
    airportCodes: ['FCO', 'MXP'],
    airportCount: 2,
    facilityCount: 3,
    strongestHubs: ['Rome Fiumicino (FCO)', 'Milan Malpensa (MXP)'],
    accessTypes: ['self-service'],
    airsideTypical: true,
    transitFriendly: true,
    pricingLevel: 'low',
    privacyLevel: 'medium',
    sleepQualityScore: 3,
    bestUseCases: [
      'Short layovers at Italian airports',
      'Budget travelers passing through Rome or Milan',
      'Passengers needing a quick rest without any booking process',
    ],
    limitations: [
      'Semi-enclosed only — not a sealed capsule',
      'Coverage limited to Italian hub airports',
      'Less sound and light isolation than fully enclosed pod brands',
    ],
    keyDifferentiator: 'The primary self-service pod brand at Italian airports — walk-in, no booking, pay by the hour at FCO and MXP.',
    amenitySignals: ['semi-enclosed design', 'reclining seat', 'hourly billing', 'no booking required', 'Italian airports'],
    compareCandidates: ['napcabs', 'gosleep', 'izzleep', 'aerotel', 'sleepover'],
    coverageNote: 'Rome Fiumicino and Milan Malpensa only. Covers the two highest-traffic Italian international airport hubs.',
    entryNuance: 'Walk up, pay at pod terminal, rest. No app or reservation system required.',
    sleepNuance: 'Reclining seat with partial privacy hood. Practical for 1–3 hour rest; not suitable for deep sleep or overnight stays.',
    trustNote: 'Italian-developed brand with multi-year deployment track record at FCO.',
  },

  'kepler-club': {
    slug: 'kepler-club',
    name: 'Kepler Club',
    type: 'lounge',
    operatorModel: 'independent',
    regions: ['Asia', 'Middle East'],
    airportCodes: ['HKG', 'DXB'],
    airportCount: 3,
    facilityCount: 3,
    strongestHubs: ['Hong Kong International (HKG)', 'Dubai International (DXB)'],
    accessTypes: ['paid-entry'],
    airsideTypical: true,
    transitFriendly: true,
    pricingLevel: 'premium',
    privacyLevel: 'low',
    sleepQualityScore: 2,
    bestUseCases: [
      'Travelers wanting a premium independent lounge without airline status',
      'Long layovers where food quality and a calm environment are the priority',
      'Passengers who find standard independent lounges underwhelming',
    ],
    limitations: [
      'Premium pricing tier — costlier than Plaza Premium or standard independent lounges',
      'Small airport footprint — limited to select locations',
      'Not a sleep product — lounge seating only',
    ],
    keyDifferentiator: 'Premium-tier independent lounge with elevated food quality and a calmer environment than standard walk-in options — no airline status required.',
    amenitySignals: ['premium food menu', 'quiet seating zones', 'showers', 'high-quality furnishings', 'paid entry', 'no status required'],
    compareCandidates: ['plaza-premium', 'miracle', 'aerotel', 'yotelair', 'sh-premium-lounge'],
    coverageNote: 'HKG and DXB are its established locations. Footprint remains narrow — limited value outside those two hub routings.',
    entryNuance: 'Paid per visit. Third-party program eligibility varies by location — confirm before assuming card access.',
    sleepNuance: 'Lounge seating with rest areas. Above-average comfort for a lounge, but not a dedicated sleep environment.',
    trustNote: 'Boutique brand with a strong reputation among business travelers at HKG and DXB for food quality and ambiance.',
  },

  'wait-n-rest': {
    slug: 'wait-n-rest',
    name: "Wait N' Rest",
    type: 'pod',
    operatorModel: 'self-service',
    regions: ['Asia'],
    airportCodes: [],
    airportCount: 1,
    facilityCount: 1,
    strongestHubs: [],
    accessTypes: ['self-service'],
    airsideTypical: true,
    transitFriendly: true,
    pricingLevel: 'low',
    privacyLevel: 'medium',
    sleepQualityScore: 2,
    bestUseCases: [
      'Budget travelers on short layovers needing basic rest',
      'Passengers who need a rest without committing to hotel pricing',
      'Walk-in same-session use without any advance planning',
    ],
    limitations: [
      'Basic pod format — partial enclosure only',
      'No shower access or hotel-level amenities',
      'Very limited airport presence',
    ],
    keyDifferentiator: 'Accessible no-frills pod rest — walk in, pay by the hour, no booking friction.',
    amenitySignals: ['self-service', 'hourly billing', 'walk-in access', 'no booking required'],
    compareCandidates: ['gosleep', 'napcabs', 'sleepover', 'izzleep', 'aerotel'],
    coverageNote: 'Very limited footprint. Check live listings on RestInAirport for confirmed current airport locations.',
    entryNuance: 'Self-service walk-in. No staff, no app, no reservation. Pay at the unit.',
    sleepNuance: 'Basic reclining surface with partial privacy. Functional for short rest — not suitable for overnight use.',
  },

  'sh-premium-lounge': {
    slug: 'sh-premium-lounge',
    name: 'SH Premium Lounge',
    type: 'lounge',
    operatorModel: 'independent',
    regions: ['Asia'],
    airportCodes: [],
    airportCount: 1,
    facilityCount: 1,
    strongestHubs: [],
    accessTypes: ['paid-entry'],
    airsideTypical: true,
    transitFriendly: true,
    pricingLevel: 'mid',
    privacyLevel: 'low',
    sleepQualityScore: 2,
    bestUseCases: [
      'Passengers without airline lounge access at its served airport',
      'Travelers wanting food, Wi-Fi, and comfortable seating during a layover',
      'Short to medium waits where a transit hotel is excessive',
    ],
    limitations: [
      'Very limited airport coverage — single location',
      'Not a dedicated sleep facility',
    ],
    keyDifferentiator: 'Accessible independent lounge with food and Wi-Fi included in the visit price — no airline membership required.',
    amenitySignals: ['food included', 'Wi-Fi', 'comfortable seating', 'paid entry', 'airside positioning'],
    compareCandidates: ['plaza-premium', 'kepler-club', 'miracle', 'skyhub-lounge', 'aerotel'],
    coverageNote: 'Single location. Verify live airport placement on RestInAirport before travel.',
    entryNuance: 'Walk-in paid entry. No airline status or card program required.',
    sleepNuance: 'Lounge seating only — not a sleep product. Suitable for resting upright during short waits.',
  },

  'skyhub-lounge': {
    slug: 'skyhub-lounge',
    name: 'Skyhub Lounge',
    type: 'lounge',
    operatorModel: 'independent',
    regions: ['Asia'],
    airportCodes: ['ICN', 'GMP'],
    airportCount: 2,
    facilityCount: 2,
    strongestHubs: ['Seoul Incheon (ICN)', 'Seoul Gimpo (GMP)'],
    accessTypes: ['paid-entry'],
    airsideTypical: true,
    transitFriendly: true,
    pricingLevel: 'mid',
    privacyLevel: 'low',
    sleepQualityScore: 2,
    bestUseCases: [
      'Passengers transiting through Seoul Incheon or Gimpo without Korean airline lounge access',
      'Layovers requiring food, Wi-Fi, and comfortable seating at Korean hubs',
      'Travelers wanting lounge access without Korean Air or Asiana credentials',
    ],
    limitations: [
      'Coverage limited to South Korea airports',
      'Lounge seating only — not a sleep facility',
    ],
    keyDifferentiator: 'The leading independent paid-entry lounge at Seoul Incheon and Gimpo — no Korean airline status required.',
    amenitySignals: ['food', 'Wi-Fi', 'comfortable seating', 'paid entry', 'Seoul hubs', 'airside'],
    compareCandidates: ['plaza-premium', 'miracle', 'sh-premium-lounge', 'kepler-club', 'aerotel'],
    coverageNote: 'ICN and GMP only. Serves the large volume of transit passengers passing through Seoul without airline lounge credentials.',
    entryNuance: 'Walk-in paid entry at both ICN and GMP locations. Airside — no Korean immigration clearance needed for transit passengers.',
    sleepNuance: 'Standard lounge seating. Rest chairs may be available but the facility is not designed as a sleep environment.',
    trustNote: 'Well-established at ICN with a consistent review track record among Seoul transit passengers.',
  },

  'sleepover': {
    slug: 'sleepover',
    name: 'Sleepover',
    type: 'pod',
    operatorModel: 'self-service',
    regions: ['Asia', 'Middle East'],
    airportCodes: [],
    airportCount: 2,
    facilityCount: 2,
    strongestHubs: [],
    accessTypes: ['self-service'],
    airsideTypical: true,
    transitFriendly: true,
    pricingLevel: 'low',
    privacyLevel: 'medium',
    sleepQualityScore: 3,
    bestUseCases: [
      'Short to medium layovers on a budget',
      'Passengers wanting walk-in pod access with no advance reservation',
    ],
    limitations: [
      'Basic pod format — partial enclosure, not a sealed capsule',
      'No shower or hotel-level amenities',
    ],
    keyDifferentiator: 'Straightforward walk-in pod rest with hourly billing and no booking requirement at its served airports.',
    amenitySignals: ['self-service', 'hourly billing', 'walk-in access', 'reclining surface', 'no booking required'],
    compareCandidates: ['gosleep', 'napcabs', 'zzzleepandgo', 'wait-n-rest', 'aerotel'],
    coverageNote: 'Limited footprint. Check live airport listings on RestInAirport for confirmed current locations.',
    entryNuance: 'Self-service walk-in. Pay at the pod terminal. No advance booking required.',
    sleepNuance: 'Reclining sleep surface with basic privacy screening. Best suited for 1–4 hour rest periods.',
  },
};
