export type BrandType = 'lounge' | 'pod' | 'hotel' | 'hybrid';

export type OperatorModel =
  | 'independent'
  | 'airline-linked'
  | 'hospitality-group'
  | 'self-service'
  | 'mixed';

export type PricingLevel = 'low' | 'mid' | 'high' | 'premium';

export type PrivacyLevel = 'low' | 'medium' | 'high';

export type SleepQualityScore = 1 | 2 | 3 | 4 | 5;

export interface BrandRecord {
  slug: string;
  name: string;
  type: BrandType;
  operatorModel: OperatorModel;
  regions: string[];
  airportCodes: string[];
  airportCount: number;
  facilityCount: number;
  strongestHubs: string[];
  accessTypes: string[];
  airsideTypical: boolean;
  transitFriendly: boolean;
  pricingLevel: PricingLevel;
  privacyLevel: PrivacyLevel;
  sleepQualityScore: SleepQualityScore;
  bestUseCases: string[];
  limitations: string[];
  keyDifferentiator: string;
  amenitySignals: string[];
  compareCandidates: string[];
  coverageNote?: string;
  entryNuance?: string;
  sleepNuance?: string;
  trustNote?: string;
  lastVerified?: string;
}

export const BRAND_DATA: Record<string, BrandRecord> = {
  'aerotel': {
    slug: 'aerotel',
    name: 'Aerotel',
    type: 'hotel',
    operatorModel: 'hospitality-group',
    regions: ['Asia', 'Middle East', 'Europe', 'South America'],
    airportCodes: ['SIN', 'LHR', 'KUL', 'MCT', 'PVG', 'MAD', 'TAO', 'HKG', 'JED', 'GIG', 'CEB', 'SYD'],
    airportCount: 12,
    facilityCount: 12,
    strongestHubs: ['Singapore Changi (SIN)', 'Hong Kong (HKG)', 'London Heathrow (LHR)', 'Kuala Lumpur (KUL)'],
    accessTypes: ['front-desk'],
    airsideTypical: false,
    transitFriendly: true,
    pricingLevel: 'premium',
    privacyLevel: 'high',
    sleepQualityScore: 5,
    bestUseCases: [
      'Layovers of 4+ hours needing real recovery',
      'Passengers who cannot exit without a visa (at airside locations)',
      'Travelers wanting a proper bed and shower mid-transit',
    ],
    limitations: [
      'Higher cost than pod options',
      'Advance booking required during peak seasons',
      'Not all locations are airside — LHR, KUL (KLIA2), SYD, CEB, and MAD are landside arrivals-hall or mixed-zone hotels',
    ],
    keyDifferentiator: 'Plaza Premium Group\'s transit hotel brand — private rooms with en-suite showers at 12 airports across Asia, Middle East, Europe, and South America. Airside-only at select hubs; verify per location.',
    amenitySignals: ['private room', 'en-suite shower', 'real bed', 'desk', 'Wi-Fi', 'hourly booking'],
    compareCandidates: ['yotelair', 'minute-suites', 'napcabs', 'gosleep', 'plaza-premium'],
    coverageNote: 'Airports: SIN (airside), HKG (airside), JED (Jeddah, airside), MCT (Muscat, airside), TAO (Qingdao, conditional), PVG (Shanghai T2, conditional), LHR (T3 Arrivals, landside), KUL (KLIA2, landside), MAD (landside), CEB (Cebu, landside), SYD (T1 Arrivals, landside), GIG (Rio de Janeiro, airside). Always confirm airside/landside status before booking.',
    entryNuance: 'Front desk booking at each location. Airside locations (SIN, HKG, JED, GIG) allow transit access without clearing immigration. Landside locations (LHR, KUL, SYD, CEB, MAD) require immigration clearance.',
    sleepNuance: 'Real hotel bed with blackout curtains and en-suite bathroom. Closest to an off-airport hotel experience inside or adjacent to a terminal.',
    trustNote: 'One of the most established transit hotel brands globally, operating as part of Plaza Premium Group. Singapore Changi location has operated since the 1990s.',
    lastVerified: '2026-03-30',
  },

  'gosleep': {
    slug: 'gosleep',
    name: 'GoSleep',
    type: 'pod',
    operatorModel: 'self-service',
    regions: ['Europe', 'Middle East', 'Asia', 'Oceania'],
    airportCodes: ['HEL', 'AMS', 'IST', 'PER', 'DXB', 'AUH', 'GYD', 'TLL', 'WAW'],
    airportCount: 9,
    facilityCount: 10,
    strongestHubs: ['Helsinki Airport (HEL)', 'Amsterdam Schiphol (AMS)', 'Dubai International (DXB)', 'Istanbul Airport (IST)'],
    accessTypes: ['self-service'],
    airsideTypical: true,
    transitFriendly: true,
    pricingLevel: 'low',
    privacyLevel: 'medium',
    sleepQualityScore: 3,
    bestUseCases: [
      'Short layovers of 1–4 hours',
      'Budget travelers who need a quick rest',
      'Passengers who want zero booking friction',
    ],
    limitations: [
      'Visor provides partial privacy only — not a sealed capsule',
      'Terminal noise remains audible through the visor',
      'No shower access built into pod units',
    ],
    keyDifferentiator: 'Finnish-designed walk-up pods with privacy visor — no check-in, no booking, operational within 60 seconds of arrival. Deployed across 9 airports in Europe, the Middle East, and Oceania.',
    amenitySignals: ['privacy visor', 'flat-recline seat', 'wake-up alarm', 'hourly billing', 'no booking needed'],
    compareCandidates: ['napcabs', 'izzleep', 'zzzleepandgo', 'aerotel', 'sleepover'],
    coverageNote: 'Airports: HEL (Helsinki), AMS (Schiphol, 2 locations), IST (Istanbul), PER (Perth), DXB (Dubai), AUH (Abu Dhabi), GYD (Baku), TLL (Tallinn), WAW (Warsaw). Operators vary by airport — individual locations are run by third-party partners licensed to use the GoSleep pod format.',
    entryNuance: 'Walk up, pay, rest. No staff interaction or advance reservation at any location.',
    sleepNuance: 'Flat-recline seat with visor — adequate for napping, not ideal for deep sleep or noise-sensitive travelers.',
    trustNote: 'Finnish-manufactured pod brand with a decade-plus track record. Now licensed to third-party operators at individual airports.',
    lastVerified: '2026-03-30',
  },

  'yotelair': {
    slug: 'yotelair',
    name: 'YOTELAIR',
    type: 'hotel',
    operatorModel: 'hospitality-group',
    regions: ['Europe', 'Asia'],
    airportCodes: ['AMS', 'LGW', 'CDG', 'SIN', 'IST'],
    airportCount: 5,
    facilityCount: 5,
    strongestHubs: ['Amsterdam Schiphol (AMS)', 'Paris CDG (CDG)', 'Singapore Changi (SIN)', 'Istanbul Airport (IST)'],
    accessTypes: ['front-desk'],
    airsideTypical: true,
    transitFriendly: true,
    pricingLevel: 'premium',
    privacyLevel: 'high',
    sleepQualityScore: 5,
    bestUseCases: [
      'Long-haul layovers on European and Asia-Pacific routes',
      'Business and premium economy travelers',
      'Passengers wanting hotel-grade rest without leaving departures',
    ],
    limitations: [
      'Premium pricing — among the most expensive airside options',
      'Cabins book out quickly at hub airports',
      'No presence in North America or the Middle East',
    ],
    keyDifferentiator: 'Fully private cabins with SmartBed, rainfall shower, and in-room entertainment — the benchmark for airside hotel quality across European and select Asian hubs.',
    amenitySignals: ['SmartBed', 'rainfall shower', 'lockable cabin', 'in-room entertainment', 'Wi-Fi', 'fresh linen'],
    compareCandidates: ['aerotel', 'minute-suites', 'napcabs', 'plaza-premium', 'kepler-club'],
    coverageNote: 'Current YOTELAIR airports: Amsterdam Schiphol (AMS), London Gatwick (LGW), Paris CDG (CDG), Singapore Changi Jewel (SIN, landside), and Istanbul Airport (IST, airside). Note: the former YOTELAIR London Heathrow is closed; the JFK New York property is a city hotel (YOTEL), not an airport transit hotel.',
    entryNuance: 'Check-in at the YOTELAIR front desk. Hourly minimum applies; overnight rates offer better per-hour value.',
    sleepNuance: 'Lockable SmartBed cabin with blackout blinds and sound insulation. Comparable sleep quality to a 3-star city hotel.',
    trustNote: 'Premium brand with strong reputation at Schiphol and CDG. Frequently cited in business travel press. Singapore property is in Jewel (landside) — transit passengers need to clear immigration to access it.',
    lastVerified: '2026-03-30',
  },

  'napcabs': {
    slug: 'napcabs',
    name: 'Napcabs',
    type: 'pod',
    operatorModel: 'independent',
    regions: ['Europe'],
    airportCodes: ['MUC', 'FRA', 'BER', 'STR'],
    airportCount: 4,
    facilityCount: 8,
    strongestHubs: ['Munich Airport T2 (MUC)', 'Frankfurt Airport (FRA)', 'Berlin Brandenburg (BER)'],
    accessTypes: ['self-service'],
    airsideTypical: true,
    transitFriendly: true,
    pricingLevel: 'mid',
    privacyLevel: 'high',
    sleepQualityScore: 4,
    bestUseCases: [
      'Light sleepers who need genuine blackout conditions',
      'Overnight layovers at German airports',
      'Travelers wanting maximum pod privacy without hotel-tier pricing',
    ],
    limitations: [
      'Concentrated in German-speaking airports — limited value on routes not passing through MUC, FRA, BER, or STR',
      'No in-cabin shower — adjacent shower facilities available at some locations',
      'Landside location at T2 Level 03 MUC is accessible without a boarding pass, but airside locations require security clearance',
    ],
    keyDifferentiator: 'Fully lockable, fully sealed capsules with genuine blackout — the highest privacy standard available in a pod format at German airports. Now at Munich, Frankfurt, Berlin, and Stuttgart.',
    amenitySignals: ['lockable door', 'blackout conditions', 'noise reduction', 'flat sleep surface', 'hourly billing'],
    compareCandidates: ['gosleep', 'izzleep', 'yotelair', 'zzzleepandgo', 'aerotel'],
    coverageNote: 'Munich (MUC) has 4 locations: T2 Level 05 near Gate H32 (Non-Schengen airside), T2 Level 04 near Gate G06 (Schengen airside), T2 Satellite Level 05 near Gate L04 (Non-Schengen airside), and T2 Level 03 public area (landside). All Munich locations are in Terminal 2 — not Terminal 1. Also operates at Frankfurt (FRA), Berlin Brandenburg (BER), and Stuttgart (STR).',
    entryNuance: 'Self-service booking at the pod terminal. No staff required. Accepts card payments.',
    sleepNuance: 'Sealed capsule with hard door — full blackout and meaningfully better noise suppression than visor designs.',
    trustNote: 'Long-running installation at MUC with a strong traveler review record for sleep quality among pod formats. Expanded to FRA, BER, and STR.',
    lastVerified: '2026-03-30',
  },

  'plaza-premium': {
    slug: 'plaza-premium',
    name: 'Plaza Premium',
    type: 'lounge',
    operatorModel: 'independent',
    regions: ['Asia', 'Middle East', 'Europe', 'North America', 'South America', 'Africa'],
    airportCodes: ['HKG', 'KUL', 'SIN', 'PEK', 'DXB', 'LHR', 'FCO', 'YVR', 'DFW', 'LAX'],
    airportCount: 80,
    facilityCount: 250,
    strongestHubs: ['Hong Kong (HKG)', 'Kuala Lumpur (KUL)', 'Singapore (SIN)', 'Rome Fiumicino (FCO)'],
    accessTypes: ['paid-entry', 'card-access'],
    airsideTypical: true,
    transitFriendly: true,
    pricingLevel: 'mid',
    privacyLevel: 'low',
    sleepQualityScore: 2,
    bestUseCases: [
      'Travelers without airline lounge access needing food and a shower',
      'Long layovers at Asia-Pacific and Middle East hub airports',
      'Passengers with Priority Pass or compatible card benefits',
    ],
    limitations: [
      'Walk-in fees can reach premium levels at peak times',
      'Not designed for sleep — rest chairs are supplementary',
      'Quality varies significantly across the 250+ location network',
    ],
    keyDifferentiator: 'The world\'s largest independent airport lounge network — 250+ locations at 80+ airports open to any passenger without airline status or ticket class restriction. Also operates the Aerotel transit hotel brand.',
    amenitySignals: ['hot food buffet', 'showers', 'Wi-Fi', 'quiet seating', 'Priority Pass eligible', 'rest zones'],
    compareCandidates: ['kepler-club', 'miracle', 'aerotel', 'yotelair', 'sh-premium-lounge'],
    coverageNote: 'Exceptional Asia-Pacific density. HKG, KUL, and SIN properties are flagship-grade. FCO (Rome) is a Skytrax award-winner. Network also covers North America (DFW, LAX, YVR), Middle East, and Africa. Individual airport pages on RestInAirport list specific terminal locations.',
    entryNuance: 'Paid walk-in, Priority Pass, Lounge Key, and select credit card access. Some locations require separate shower booking on arrival.',
    sleepNuance: 'Rest chairs available but not dedicated sleep infrastructure. Lounge seating — not a pod or room product.',
    trustNote: 'Global benchmark for independent lounge access. Widely integrated into credit card travel benefits programs. Parent company also operates Aerotel transit hotels.',
    lastVerified: '2026-03-30',
  },

  'minute-suites': {
    slug: 'minute-suites',
    name: 'Minute Suites',
    type: 'hotel',
    operatorModel: 'independent',
    regions: ['North America'],
    airportCodes: ['ATL', 'PHL', 'DFW', 'CLT', 'BWI', 'DTW', 'EWR', 'IAH', 'JFK', 'BNA', 'SLC'],
    airportCount: 11,
    facilityCount: 17,
    strongestHubs: ['Atlanta Hartsfield-Jackson (ATL)', 'Dallas Fort Worth (DFW)', 'John F. Kennedy (JFK)', 'Charlotte Douglas (CLT)'],
    accessTypes: ['front-desk'],
    airsideTypical: true,
    transitFriendly: false,
    pricingLevel: 'mid',
    privacyLevel: 'high',
    sleepQualityScore: 4,
    bestUseCases: [
      'Business travelers needing a private space for calls or work during a US layover',
      'Families with young children on domestic connections',
      'Anyone needing guaranteed quiet and privacy at a US hub airport',
    ],
    limitations: [
      'US domestic terminal coverage only — no value for international routing',
      'Shower is an optional add-on, not standard in base rate',
      'All locations past TSA security — must have a valid boarding pass to access',
    ],
    keyDifferentiator: 'The only private enclosed day suite product with a national footprint inside the US domestic terminal network — 17 locations across 11 airports as of 2026.',
    amenitySignals: ['daybed sofa', 'work desk', 'television', 'Wi-Fi', 'fully enclosed suite', 'hourly billing', 'optional shower add-on'],
    compareCandidates: ['aerotel', 'yotelair', 'napcabs', 'gosleep', 'kepler-club'],
    coverageNote: 'US locations: ATL (3 locations: Concourse B, E, F), BWI (Concourse C), CLT (2 locations), DFW (Terminal A and D), DTW (Concourse A), EWR (Terminal C), IAH (Terminal C North), JFK (Terminal 4 and 8), BNA (Concourse D), PHL (A/B Connector), SLC (Concourse A). All locations are past TSA security airside.',
    entryNuance: 'Front desk booking — walk-in or advance reservation. Minimum one hour, no mandatory multi-hour window.',
    sleepNuance: 'Daybed converts to flat sleep surface. Fully enclosed with door lock. Quiet HVAC. Functional for proper napping or short overnight.',
    trustNote: 'Well-regarded among US frequent domestic travelers. Consistent positive reviews for privacy and convenience. Expanded significantly in 2024–2025.',
    lastVerified: '2026-03-30',
  },

  'miracle': {
    slug: 'miracle',
    name: 'Miracle',
    type: 'lounge',
    operatorModel: 'independent',
    regions: ['Asia'],
    airportCodes: ['BKK', 'DMK'],
    airportCount: 2,
    facilityCount: 9,
    strongestHubs: ['Bangkok Suvarnabhumi (BKK)', 'Bangkok Don Mueang (DMK)'],
    accessTypes: ['paid-entry'],
    airsideTypical: true,
    transitFriendly: true,
    pricingLevel: 'mid',
    privacyLevel: 'low',
    sleepQualityScore: 2,
    bestUseCases: [
      'Passengers transiting through Bangkok Suvarnabhumi needing food and a shower',
      'Travelers without Thai Airways or Bangkok Airways lounge credentials',
      'Anyone wanting a premium break at BKK without airline status',
    ],
    limitations: [
      'Two-airport brand — only at Bangkok Suvarnabhumi (BKK) and Don Mueang (DMK)',
      'Rest zones are lounge seating only, not dedicated sleep pods',
      'Quality and crowding varies across the 9 facilities',
    ],
    keyDifferentiator: 'Dominant independent lounge operator at Bangkok\'s two airports — multiple tier locations spread across BKK and DMK terminals, open to any passenger.',
    amenitySignals: ['Business Class tier', 'First Class tier', 'hot food', 'showers', 'rest chairs', 'airside access'],
    compareCandidates: ['plaza-premium', 'kepler-club', 'encalm', 'sh-premium-lounge', 'skyhub-lounge'],
    coverageNote: 'At BKK: lounges in Concourses A, C, D, and G (multiple entrances), plus domestic. At DMK: domestic departures. At least 9 distinct Miracle Lounge facilities across both airports.',
    entryNuance: 'Paid per visit, tiered pricing by lounge class. Walk-in available; pre-booking via lounge platforms recommended during peak season.',
    sleepNuance: 'Rest chairs in designated zones — not a dedicated sleep product. Suitable for upright napping during a 2–4 hour transit.',
    trustNote: 'Established Bangkok institution with long operating history. Frequently recommended by Thailand transit travelers in travel forums.',
    lastVerified: '2026-03-30',
  },

  'izzleep': {
    slug: 'izzleep',
    name: 'izZzleep',
    type: 'pod',
    operatorModel: 'independent',
    regions: ['North America'],
    airportCodes: ['MEX'],
    airportCount: 1,
    facilityCount: 2,
    strongestHubs: ['Mexico City Benito Juárez (MEX)'],
    accessTypes: ['self-service'],
    airsideTypical: false,
    transitFriendly: false,
    pricingLevel: 'low',
    privacyLevel: 'high',
    sleepQualityScore: 4,
    bestUseCases: [
      'Travelers connecting at Mexico City airport needing rest between flights',
      'Budget travelers who want pod enclosure without hotel pricing',
      'Passengers needing rest at MEX during long domestic or international connections',
    ],
    limitations: [
      'Available only at Mexico City Airport (MEX), Terminal 1 and Terminal 2',
      'Facilities are landside — a boarding pass is not required but the location is not airside transit',
      'No shower access within the capsule units',
    ],
    keyDifferentiator: 'Fully enclosed climate-controlled sleep pods at Mexico City Airport — the only enclosed pod rest option at MEX, across two terminals.',
    amenitySignals: ['fully enclosed capsule', 'climate control', 'adjustable lighting', 'flat sleep surface', 'hourly billing'],
    compareCandidates: ['gosleep', 'napcabs', 'zzzleepandgo', 'aerotel', 'sleepover'],
    coverageNote: 'Two facilities: Terminal 1 (40 cubicles) and Terminal 2 (47 pods) at Mexico City Benito Juárez International Airport. Both are landside. Accessible without a boarding pass.',
    entryNuance: 'Self-service booking. Both Terminal 1 and Terminal 2 locations are accessible landside — no boarding pass required.',
    sleepNuance: 'Full enclosure with door seal. Climate control and adjustable lighting allow real sleep customization unavailable in visor-type pods.',
    trustNote: 'Well-reviewed on booking.com and sleepinginairports.net for the MEX locations. A practical option for Mexico City connections.',
    lastVerified: '2026-03-30',
  },

  'encalm': {
    slug: 'encalm',
    name: 'Encalm',
    type: 'hybrid',
    operatorModel: 'hospitality-group',
    regions: ['Asia'],
    airportCodes: ['DEL', 'HYD', 'GOI'],
    airportCount: 3,
    facilityCount: 12,
    strongestHubs: ['Delhi Indira Gandhi International (DEL)', 'Hyderabad Rajiv Gandhi (HYD)', 'Goa Manohar (GOI)'],
    accessTypes: ['paid-entry', 'front-desk'],
    airsideTypical: true,
    transitFriendly: true,
    pricingLevel: 'mid',
    privacyLevel: 'high',
    sleepQualityScore: 4,
    bestUseCases: [
      'Passengers transiting through Delhi, Hyderabad, or Goa with a 3–12 hour layover',
      'Travelers who want to select rest tier (lounge, pod, or room) at one operator',
      'Those needing a full-service facility without navigating multiple brands',
    ],
    limitations: [
      'Indian airport coverage only — DEL, HYD, and GOI',
      'Peak-season availability at pod and hotel room tiers requires advance booking',
    ],
    keyDifferentiator: "India's largest transit hospitality operator — lounge, sleep pod, and hotel room available under one brand at multiple Indian airports including DEL, HYD, and GOI.",
    amenitySignals: ['lounge tier', 'pod tier', 'hotel room tier', 'showers', 'hot food', 'tiered pricing'],
    compareCandidates: ['miracle', 'plaza-premium', 'aerotel', 'kepler-club', 'sh-premium-lounge'],
    coverageNote: 'Delhi (DEL) has the largest presence: Encalm Lounge at T1, T2, T3 International, T3 Domestic, and T3 Arrivals; Encalm Privé (premium tier) at T3 International; Transit by Encalm (nap/shower rooms) at T3 Arrivals. Also operates at Hyderabad (HYD) and Goa (GOI).',
    entryNuance: 'Lounge access is walk-in paid entry. Pod and hotel room tiers are booked at reception or online. Confirm which tier and terminal before arrival.',
    sleepNuance: 'Hotel room tier offers full private room with proper bed and shower. Pod tier offers enclosed capsule sleep. Lounge tier offers rest chairs only.',
    trustNote: 'Leading transit hospitality operator in the Indian airport market. Well-reviewed for its multi-tier flexibility. Rapidly expanding domestic footprint.',
    lastVerified: '2026-03-30',
  },

  'zzzleepandgo': {
    slug: 'zzzleepandgo',
    name: 'ZZZleepandGo',
    type: 'pod',
    operatorModel: 'self-service',
    regions: ['Europe'],
    airportCodes: ['VIE', 'VRN', 'TRN', 'VCE', 'WMI', 'BGY'],
    airportCount: 6,
    facilityCount: 6,
    strongestHubs: ['Vienna International (VIE)', 'Venice Marco Polo (VCE)', 'Milan Bergamo (BGY)'],
    accessTypes: ['self-service'],
    airsideTypical: false,
    transitFriendly: false,
    pricingLevel: 'low',
    privacyLevel: 'medium',
    sleepQualityScore: 3,
    bestUseCases: [
      'Short layovers at European secondary and regional airports',
      'Passengers needing a quick rest without any booking process',
      'Budget travelers connecting through Austrian, Italian, or Polish airports',
    ],
    limitations: [
      'All locations are landside — accessible in arrivals or departures areas, not in transit airside zones',
      'Semi-enclosed capsule design — not a fully sealed pod',
      'Less useful for transit-only passengers who cannot clear immigration',
    ],
    keyDifferentiator: 'Self-service sleep capsules deployed across 6 European airports including Vienna, Venice, Verona, Turin, Milan Bergamo, and Warsaw Modlin — walk-in, no booking, pay by the hour.',
    amenitySignals: ['semi-enclosed capsule', 'reclining surface', 'hourly billing', 'no booking required', 'European airports'],
    compareCandidates: ['napcabs', 'gosleep', 'izzleep', 'aerotel', 'sleepover'],
    coverageNote: 'Airports: VIE (Vienna, Arrivals), VRN (Verona, Arrivals), TRN (Turin, Departures), VCE (Venice, Departures), WMI (Warsaw Modlin, Departures), BGY (Bergamo, Terminal). All locations are landside. MXP (Milan Malpensa) may also be active — verify current listings.',
    entryNuance: 'Walk up, pay at pod terminal, rest. No app or reservation system required. All locations are landside — immigration clearance may be required before accessing these areas.',
    sleepNuance: 'Capsule with partial privacy. Practical for 1–3 hour rest; not suitable for deep sleep or overnight stays.',
    trustNote: 'Italian-developed brand with confirmed deployments at 6 European airports including Vienna and Venice.',
    lastVerified: '2026-03-30',
  },

  'kepler-club': {
    slug: 'kepler-club',
    name: 'Kepler Club',
    type: 'lounge',
    operatorModel: 'independent',
    regions: ['Europe', 'Asia'],
    airportCodes: ['SAW', 'RIX', 'KUL'],
    airportCount: 3,
    facilityCount: 4,
    strongestHubs: ['Istanbul Sabiha Gokcen (SAW)', 'Riga International (RIX)', 'Kuala Lumpur (KUL)'],
    accessTypes: ['paid-entry'],
    airsideTypical: true,
    transitFriendly: true,
    pricingLevel: 'premium',
    privacyLevel: 'low',
    sleepQualityScore: 2,
    bestUseCases: [
      'Travelers wanting a premium independent lounge without airline status',
      'Long layovers where food quality and a calm environment are the priority',
      'Passengers routing through Istanbul Sabiha Gokcen, Riga, or Kuala Lumpur',
    ],
    limitations: [
      'Premium pricing tier — costlier than standard independent lounges',
      'Small airport footprint — limited to SAW, RIX, and KUL',
      'Not a sleep product — lounge seating only',
    ],
    keyDifferentiator: 'Premium-tier independent lounge with elevated food quality and a calmer environment — available at Istanbul Sabiha Gokcen (SAW), Riga (RIX), and Kuala Lumpur (KUL). No airline status required.',
    amenitySignals: ['premium food menu', 'quiet seating zones', 'showers', 'high-quality furnishings', 'paid entry', 'no status required'],
    compareCandidates: ['plaza-premium', 'miracle', 'aerotel', 'yotelair', 'sh-premium-lounge'],
    coverageNote: 'Three airports: Istanbul Sabiha Gokcen (SAW), Riga International (RIX — both airside and landside), and Kuala Lumpur International (KUL — both airside Satellite Building and landside Main Terminal). Note: previous data listed HKG and DXB — those are not Kepler Club locations.',
    entryNuance: 'Paid per visit. Third-party program eligibility varies by location — Mastercard Airport Experiences confirmed at KUL. Confirm access method before arrival.',
    sleepNuance: 'Lounge seating with rest areas. Above-average comfort for a lounge, but not a dedicated sleep environment.',
    trustNote: 'Turkish-founded boutique brand (Kepler Dinlenme Hizmetleri A.S.) with a strong reputation for food quality and ambiance at its served airports.',
    lastVerified: '2026-03-30',
  },

  'wait-n-rest': {
    slug: 'wait-n-rest',
    name: "Wait N' Rest",
    type: 'pod',
    operatorModel: 'self-service',
    regions: ['North America', 'South America'],
    airportCodes: ['BOG', 'MIA', 'YYZ'],
    airportCount: 3,
    facilityCount: 3,
    strongestHubs: ['Miami International (MIA)', 'Bogotá El Dorado (BOG)'],
    accessTypes: ['self-service'],
    airsideTypical: true,
    transitFriendly: true,
    pricingLevel: 'low',
    privacyLevel: 'medium',
    sleepQualityScore: 3,
    bestUseCases: [
      'Travelers at MIA or BOG needing rest during a layover',
      'Budget travelers who need a rest without committing to hotel pricing',
      'Walk-in same-session use without any advance planning',
    ],
    limitations: [
      'Limited to Bogotá, Miami, and Toronto (expanding)',
      'Pod format — partial enclosure only',
      'No shower access or hotel-level amenities',
    ],
    keyDifferentiator: 'Americas-focused sleep pod brand — airside self-service pods at Bogotá El Dorado (BOG, the original), Miami International (MIA, opened 2025), and Toronto Pearson (YYZ, expanding).',
    amenitySignals: ['self-service', 'hourly billing', 'walk-in access', 'airside position', 'no booking required'],
    compareCandidates: ['gosleep', 'napcabs', 'sleepover', 'izzleep', 'aerotel'],
    coverageNote: 'BOG: Terminal 1, Gate A13, airside (international/transit). MIA: Concourse D near Gate D15, airside past TSA (15 rooms / 30 beds). YYZ: listed on homepage as an active or upcoming location. MIA opened in 2025 as the first North American location.',
    entryNuance: 'Self-service walk-in. No app, no reservation. Pay at the unit. All locations are airside — a valid boarding pass is required.',
    sleepNuance: 'Pod-format reclining surface with partial privacy. Functional for 1–4 hour rest periods.',
    lastVerified: '2026-03-30',
  },

  'sh-premium-lounge': {
    slug: 'sh-premium-lounge',
    name: 'SH Premium Lounge',
    type: 'lounge',
    operatorModel: 'independent',
    regions: ['Asia'],
    airportCodes: ['HAN', 'SGN', 'DAD', 'CXR', 'HPH'],
    airportCount: 10,
    facilityCount: 20,
    strongestHubs: ['Hanoi Noi Bai (HAN)', 'Ho Chi Minh City (SGN)', 'Da Nang (DAD)'],
    accessTypes: ['paid-entry', 'card-access'],
    airsideTypical: true,
    transitFriendly: true,
    pricingLevel: 'low',
    privacyLevel: 'low',
    sleepQualityScore: 2,
    bestUseCases: [
      'Passengers transiting through Vietnamese airports without airline lounge access',
      'Travelers on domestic Vietnamese routes wanting comfort during a connection',
      'Priority Pass and Amex cardholders routing through Vietnam',
    ],
    limitations: [
      'Coverage is Vietnam-only — no value for routes outside Vietnamese airports',
      'Not a dedicated sleep facility — lounge seating only',
      'Quality and capacity varies significantly across domestic and international terminals',
    ],
    keyDifferentiator: "Vietnam's largest independent airport lounge operator — 20+ facilities across 10+ Vietnamese airports including Hanoi (HAN), Ho Chi Minh City (SGN), and Da Nang (DAD). Accessible via Priority Pass, Amex, and paid walk-in.",
    amenitySignals: ['food included', 'Wi-Fi', 'comfortable seating', 'paid entry', 'Priority Pass eligible', 'airside positioning'],
    compareCandidates: ['plaza-premium', 'kepler-club', 'miracle', 'skyhub-lounge', 'aerotel'],
    coverageNote: 'Confirmed airports: HAN (multiple lounges across domestic and international), SGN (domestic T3), DAD (Da Nang), CXR (Cam Ranh/Nha Trang), HPH (Hai Phong Cat Bi), plus Hue (HUI), Dien Bien (DIN), Chu Lai (VCL), Can Tho, and Phu Quoc. Vietnam\'s national independent lounge network.',
    entryNuance: 'Paid walk-in or via Priority Pass, Lounge Key, and select Amex/bank cards at eligible locations. Confirm your card\'s eligibility at the specific terminal before assuming access.',
    sleepNuance: 'Lounge seating only — not a sleep product. Suitable for resting upright during short waits.',
    lastVerified: '2026-03-30',
  },

  'skyhub-lounge': {
    slug: 'skyhub-lounge',
    name: 'Skyhub Lounge',
    type: 'lounge',
    operatorModel: 'independent',
    regions: ['Asia'],
    airportCodes: ['ICN', 'GMP'],
    airportCount: 2,
    facilityCount: 4,
    strongestHubs: ['Seoul Incheon T1 East Wing (ICN)', 'Seoul Incheon T2 (ICN)', 'Seoul Gimpo (GMP)'],
    accessTypes: ['paid-entry'],
    airsideTypical: true,
    transitFriendly: true,
    pricingLevel: 'mid',
    privacyLevel: 'low',
    sleepQualityScore: 2,
    bestUseCases: [
      'Passengers transiting through Seoul Incheon or Gimpo without Korean airline lounge access',
      'Layovers requiring food, Wi-Fi, and comfortable seating at Seoul hubs',
      'Travelers wanting lounge access without Korean Air or Asiana credentials',
    ],
    limitations: [
      'Coverage limited to South Korea airports',
      'Lounge seating only — not a sleep facility',
    ],
    keyDifferentiator: 'The leading independent paid-entry lounge at Seoul Incheon and Gimpo — multiple facilities at ICN across Terminal 1 and Terminal 2, plus GMP. No Korean airline status required.',
    amenitySignals: ['food', 'Wi-Fi', 'comfortable seating', 'paid entry', 'Seoul hubs', 'airside'],
    compareCandidates: ['plaza-premium', 'miracle', 'sh-premium-lounge', 'kepler-club', 'aerotel'],
    coverageNote: 'ICN has 3 Skyhub Lounge facilities: T1 East Wing, T1 West Wing, and T2 (near Gate 268, 4th floor). GMP has 1 facility (International Departure, near Gate 35). Total: 4 facilities across 2 airports.',
    entryNuance: 'Walk-in paid entry at all locations. Airside — no Korean immigration clearance needed for transit passengers.',
    sleepNuance: 'Standard lounge seating. Rest chairs may be available but the facility is not designed as a sleep environment.',
    trustNote: 'Well-established at ICN with a consistent review track record among Seoul transit passengers.',
    lastVerified: '2026-03-30',
  },

  'sleepover': {
    slug: 'sleepover',
    name: 'Sleepover',
    type: 'pod',
    operatorModel: 'self-service',
    regions: ['Middle East', 'South America'],
    airportCodes: ['DXB', 'DOH', 'LIM'],
    airportCount: 3,
    facilityCount: 8,
    strongestHubs: ['Dubai International (DXB)', 'Doha Hamad International (DOH)', 'Lima Jorge Chávez (LIM)'],
    accessTypes: ['self-service'],
    airsideTypical: true,
    transitFriendly: true,
    pricingLevel: 'low',
    privacyLevel: 'medium',
    sleepQualityScore: 3,
    bestUseCases: [
      'Transit passengers at DXB or DOH needing rest between Gulf connections',
      'Short to medium layovers on a budget',
      'Passengers wanting walk-in pod access with no advance reservation',
    ],
    limitations: [
      'Pod format — partial enclosure, not a sealed capsule',
      'No shower or hotel-level amenities',
      'Best suited to 1–6 hour layovers rather than full overnight stays',
    ],
    keyDifferentiator: 'The dominant self-service pod brand at Dubai (DXB) and Doha (DOH) — 8 facilities across three airports, all airside, rebranded from the former sleep \'n fly brand.',
    amenitySignals: ['self-service', 'hourly billing', 'walk-in access', 'reclining surface', 'no booking required', 'airside position'],
    compareCandidates: ['gosleep', 'napcabs', 'zzzleepandgo', 'wait-n-rest', 'aerotel'],
    coverageNote: 'DXB: 4 airside facilities (T1 D-Gates, T3 A-Gates, T3 B-Gates, T3 C-Gates). DOH: 3 airside facilities (North Node C30, North Node C40, South Node). LIM: 1 facility (Lima, opened early 2025). Rebranded from sleep \'n fly in 2024.',
    entryNuance: 'Self-service walk-in. Pay at the pod terminal. No advance booking required. All locations are airside — transit passengers at DXB and DOH can access without clearing immigration.',
    sleepNuance: 'Reclining sleep surface with basic privacy screening. Best suited for 1–6 hour rest periods. Not designed for overnight full-sleep stays.',
    lastVerified: '2026-03-30',
  },
};
